export const types = {
    TASK_CONFIRMATION: 'TASK_CONFIRMATION',
    TASK_CONFIRMED: 'TASK_CONFIRMED',
    AWARD_CONFIRMATION: 'AWARD_CONFIRMATION',
    AWARD_CONFIRMED: 'AWARD_CONFIRMED',
    TASK_NEW: 'TASK_NEW',
    AWARD_NEW: 'AWARD_NEW',
};
