const types = {
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    ADD_ALL_NOTIFICATIONS: 'ADD_ALL_NOTIFICATIONS',
};

export default types;
